# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e1a9070f590d95cb892f124cf197619b2da3f4d24fe5ccc0cf41a3f007e57c1f93508cb73c0ab2b462bdb8ced57737eb3679033f7a7f2deb46fb30932b978b

test:
  secret_key_base: 9575d9fd37d989aa7ddaeef547d80db146d76172e1ce47887a9566d6bb333231e49963aae45ac5e7e0bd8396baddec1304af3d8f9c076b6ecafbacb5b9ede75a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
